#!/home/elijah/.local/share/pipx/venvs/argostranslate/bin/python

import os
os.environ.setdefault("ARGOS_CHUNK_TYPE", "MINISBD")
import sys
import argostranslate.translate as t

langs = {l.code: l for l in t.get_installed_languages()}
tr = {("en", "ru"): langs["en"].get_translation(langs["ru"]),
      ("ru", "en"): langs["ru"].get_translation(langs["en"])}
for x in tr.values():
    x.translate("warm up")

for line in sys.stdin:
    src, dst, text = line.rstrip("\n").split("\t", 2)
    print(tr[(src, dst)].translate(text).replace("\n", " "), flush=True)
